# Generated by Django 3.2 on 2021-05-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_slug_article_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='slug',
        ),
    ]
