# Generated by Django 3.2 on 2021-05-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_url_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='url',
        ),
    ]
